### ISSUE TITLE
Yocto Kirkstone support

### ISSUE THREAD

**Issue by morten-bruun-zoetis** [ADLINK/meta-adlink-nxp#25]
Are there any plans to support the Kirkstone release?

**Comment by ADLINK-EPM** [comment]
@morten-bruun-zoetis  
  sorry for the late reponse. 
  Yes, we plan to have it by Oct. 
  Please stay tuned.

Ryan

**Comment by morten-bruun-zoetis** [comment]
Thanks Ryan!

I have tried the Kirkstone release and I'm having a few problems using it. I have created the issue #28 which is just a warning and should be a quick fix.
