### ISSUE TITLE
ethernet@30bf0000 not working with Yocto Hardknott BSP on lec-imx8mp

### ISSUE THREAD

**Issue by marcoventurinialfamation** [ADLINK/meta-adlink-nxp#26]
Hello, 
I tried the Yocto Hardknott BSP on a lec-imx8mp SMARC module from adlink on a LEC-BASE-R1 board.
When an ethernet cable is connected to the board the link is never shown as up, ethtool reports link down.
By reading the Basic Mode Status Register (using phytool) of the PHY, instead is possible to notice that the link status is reported correctly, and on the other side of the cable the PC reports again correctly the negotiation and the link status.

By using the Zeus BSP on the same hardware everything works flawlessly.

**Comment by ADLINK-EPM** [comment]
Hello, 
 
 Thanks for your sharing.
 We're duplicating this issue and get back to you soon
 Maybe something would be confgirued on hardknott branch.

 Ryan

**Comment by AdlinkCCoE** [comment]
> Hello, I tried the Yocto Hardknott BSP on a lec-imx8mp SMARC module from adlink on a LEC-BASE-R1 board. When an ethernet cable is connected to the board the link is never shown as up, ethtool reports link down. By reading the Basic Mode Status Register (using phytool) of the PHY, instead is possible to notice that the link status is reported correctly, and on the other side of the cable the PC reports again correctly the negotiation and the link status.
> 
> By using the Zeus BSP on the same hardware everything works flawlessly.

Can you share the COMMIT ID  or TAG ID you used for building hardknott Image

**Comment by sayooj-t** [comment]
I'm also facing the same issue. is it resolved?

**Comment by ADLINK-COM** [comment]
The issue has been resolved in the latest branch: https://github.com/ADLINK/meta-adlink-nxp/tree/scarthgap. You can try to build the image using the latest Yocto branch "Scarthgap"
