### ISSUE TITLE
Kirkstone: patches do not apply cleanly

### ISSUE THREAD

**Issue by morten-bruun-zoetis** [ADLINK/meta-adlink-nxp#28]
When I build the u-boot-imx recipe from the Kirkstone branch I get the following warning:

WARNING: u-boot-imx-2022.04-r0 do_patch: Fuzz detected:

Applying patch 0002-u-boot-modify-Kconfig-Makefile-to-build-lec-imx8mp.patch

When trying to use devtool (devtool modify u-boot-imx) this also fails - is this related to the problematic patches?

**Comment by jasonpritchard** [comment]
Appears to have been an upstream change. FWIW, I was able to get it to apply by changing line 25 of the patch to be:

```
	imxrt1020-evk.dtb \
```

I haven't been able to get it to boot yet, but at least now I get clean builds.
