### ISSUE TITLE
Error building Kirkstone for the IMX8MP

### ISSUE THREAD

**Issue by NicolasPepinHermann-Zoetis** [ADLINK/meta-adlink-nxp#29]
Hi,

I adapted [the documentation provided in the repo](https://github.com/ADLINK/meta-adlink-nxp/wiki/01-1.-Build-Yocto-Image_imx8mp) to build a Kirkstone image for the IMX8MP and I get an error during the build. **I kept the source with no modifications** in hopes to have a build that passes successfully before starting to tweak around.

The `bitbake imx-image-multimedia` commands starts building the image, and return after this error:
```
ERROR: Task (/home/pepinhen/mol-from-adlink-repo/vetscan-mol-instrument/sources/poky/meta/recipes-devtools/libtool/libtool-native_2.4.7.bb:do_install) failed with exit code '1'
```
Please note that I've attached the log of the failing recipe to the message.

Here are the commands I ran starting from an empty folder:
```
$ repo init -u https://github.com/ADLINK/adlink-manifest -b lec-imx-yocto-kirkstone -m adlink-lec-imx8mp-yocto-kirkstone_1v0.xml
$ repo sync
$ MACHINE=lec-imx8mp DISTRO=fsl-imx-wayland source adlink-imx-setup-release.sh -b build
$ bitbake imx-image-multimedia
```

Does anyone reported this error already and have you got anyone knowing how to fix it?

Nico.

[log.do_install.571078.txt](https://github.com/ADLINK/meta-adlink-nxp/files/10756655/log.do_install.571078.txt)

**Comment by ADLINK-COM** [comment]
It is expected in a bitbake environment. You can clean the particular recipe and build the image again.
$ bitbake -c cleanall libtool-native
