### ISSUE TITLE
error in manifest file of hardknott

### ISSUE THREAD

**Issue by htmlwebdesign** [ADLINK/meta-adlink-nxp#30]
whenever i try to run this command error is occured 
repo init -u https://github.com/ADLINK/adlink-manifest -b lec-imx-yocto-hardknott -m adlink-lec-imx8mp-yocto-hardknott_1v5.xml

this error occur ;-
error: Cannot checkout meta-imx: ManifestInvalidRevisionError: revision refs/tags/rel_imx_5.4.70_2.3.0 in meta-imx not found
error: in `sync`: revision refs/tags/rel_imx_5.4.70_2.3.0 in meta-imx not found

please provide the updated .xml for hardknott

**Comment by ADLINK-COM** [comment]
Here is the updated manifest file, https://github.com/ADLINK/adlink-manifest/blob/lec-imx-yocto-hardknott/adlink-lec-imx8mp-yocto-hardknott_1v5.xml
