### ISSUE TITLE
Yocto Harknott image and saveenv from u-boot

### ISSUE THREAD

**Issue by gnulux** [ADLINK/meta-adlink-nxp#32]
I have build core-image-mininal succesfully . However it is not possible to save variable from U-BOOT 
When i try "saveenv" i have this message :

`Environment size: 2331/4092 bytes
u-boot=> saveenv
Saving Environment to MMC... Writing to MMC(2)... MMC: block number 0x2008 exceeds max(0x2000)
failed
Failed (1)`

How to solve this issue ?

**Comment by gnulux** [comment]
Hi ,
I still not can save my env when booting from eMMc

**Comment by kkraman02** [comment]
If you boot from an SD card, you might get the error. Flash the image on the eMMC and boot from eMMC; the problem will be gone.
