### ISSUE TITLE
why depends on meta-adlink-demo?

### ISSUE THREAD

**Issue by droppingin** [ADLINK/meta-adlink-nxp#33]
Hello,

first of all, thank you for the layers.
I have a couple of questions though.

I am building a custom headless image (no ui, only console) based on kirkstone.
When i bind `meta-adlink-nxp`, i am forced to use `adlink-demo` because of [LAYERDEPENDS_adlink-nxp = "adlink-demo"](https://github.com/ADLINK/meta-adlink-nxp/blob/d54ef1db1fe21c28147877cebf9e2e2849d47948/conf/layer.conf#L13C40-L14C1) which does not look right to me as i don't want to download any additional dependencies.
As far as i understood, the *demo*-layer brings some default functionality, additional settings, UI and so on.

* Why does the meta-adlink-*nxp* depend on meta-adlink-*demo*?
* How can i disable/exclude it in my build?

**Comment by po-cheng-adlink** [comment]
You can remove LAYERDEPENDS line, and just BBMASK the bbappend recipes that originated in the meta-adlink-demo layer
