### ISSUE TITLE
X application can't run due to "unable to open display"

### ISSUE THREAD

**Issue by HiroAtech** [ADLINK/meta-adlink-nxp#78]
Hi,
I successfully bitbaked scarthgap following the instruction found at https://github.com/ADLINK/meta-adlink-nxp/wiki/Building-Yocto-for-LEC%E2%80%90IMX8MP and saw desktop successfully start and open 2 xterms. However when I tried to run x11perf, I encoundered the error message "unable to open display". So I set ":0.0" to DISPLAY variable by issuing the command export DISPLAY=:0.0 on an xterm then tried to run x11perf again but in vain. How can I fix this issue? Please also find the attached for refernce.
Best Regards, 
![X failed](https://github.com/user-attachments/assets/04f1b09c-df7d-4f2b-92ac-492cd19bae16)

**Comment by AdlinkCCoE** [comment]
Hi HiroAtech,

Please follow below steps.

1. edit file /etc/xdg/weston/weston.ini and uncomment xwayland=true
     - #xwayland=true
     +  xwayland=true
2. save file and Reboot module to apply changes

Please refer below x11perf output 

![Media](https://github.com/user-attachments/assets/0cf2091d-84fd-43ac-92d7-bafdf518c203)

Thanks

**Comment by HiroAtech** [comment]
Hi,
 Thanks for help. I could see x11perf run simply after modifying the weston.ini as mentioned.
Regards,

**Comment by HiroAtech** [comment]
Hi,

Thanks for help. I could see x11perf run simply after modifying the weston.ini as mentioned.
Please close this case.

Regards,
